### ISSUE TITLE
VALSET example

### ISSUE THREAD

**Issue by andreamancuso** [arobenko/cc.ublox.commsdsl#11]
Hi @arobenko 

Are there any examples on how to construct a VALSET programmatically?

This is what I came up with so far

```
using OutCfgValset = cc_ublox::message::CfgValset<OutMessage>;

OutCfgValset msg;
auto& layers = msg.field_layers();
auto& cfgData = msg.field_cfgdata();

cc_ublox::message::CfgValsetFields<>::Cfgdata a;

cc_ublox::field::CfgValPairSimple b;

b.field_key().setValue(0xa2);
b.field_val().setValue(1);

cfgData.setValue(b);

layers.setBitValue_ram(true);

sendMessage(msg);
```

The compiler doesn't quite like that.

Thank you in advance!

**Comment by andreamancuso** [comment]
Meanwhile I sent hand-crafted VALSETs and managed to enable NAV-POSLLH and NAV-PVT on an M10 EVK. I can parse both without any issues!

**Comment by arobenko** [comment]
### Short Answer
The [tutorial4](https://github.com/commschamp/cc_tutorial/tree/master/tutorials/tutorial4) explains how to access the `<variant>`'s fields. To assign the `cfgdata` field as needed should probably look like this:
```cpp
OutCfgValset msg;
auto& cfgData = msg.field_cfgdata();

using KeyType = OutCfgValset::Field_cfgdata::Field_key::ValueType;
cfgData.field_key().setValue(KeyType::CFG_MSGOUT_UBX_NAV_POSLLH_UART1);
cfgData.field_val().initField_cfgValL().setValue(1); // select (initialize) proper variant member and then set the value
```

### Longer Answer
In the spirit of the commsdsl the definition of the `CfgValset` message should have referenced `CfgValPair` instead of `CfgValPairSimple`. However, such definition was too heavy for some compilers to handle, especially with development computers with less than 16GB of memory. Another less boilerplate (not enforcing the length of the `val` field) code, although much heavier on compiler and probably runtime could look like this (not really tested, might not even compile):
```cpp
#include "comms/util/cast.h"
...
cc_ublox::field::CfgValPair<> pairField;
auto& posllhMem = pairField.initField_msgoutUbxNavPosllhUart1();
posllhMem.field_val().setValue(1);

OutCfgValset msg;
msg.field_cfgdata() = comms::field_cast<OutCfgValset::Field_cfgdata>(pairField);
```

The cast function is documented [here](https://commschamp.github.io/comms_doc/namespacecomms.html#a503a7696e8a2d355614c52f5f01db177) and explained in the [tutorial21](https://github.com/commschamp/cc_tutorial/tree/master/tutorials/tutorial21).

### In General
To resolve a burden of using a very small subset of the protocol functionality, especially having a long list of `<variant>` members, (somehow) allowing selection of the custom list of the variant members during the code generation is on my future **TODO** list. If I come around to implement it, then maybe the definition of the protocol may change to include `CfgValPair` field instead of `CfgValPairSimple`.

**Comment by andreamancuso** [comment]
Thank you for your comprehensive answer. 👍

**Comment by andreamancuso** [comment]
This is likely due to me being thick - here's how I got it working

```
void Session::sendValSetWithSingleKeyValuePair(CfgValKeyId valKeyId, long valValue) {
    using CfgdataElement = cc_ublox::message::CfgValsetFields<>::CfgdataMembers::Element;

    OutCfgValset msg;
    auto& layers = msg.field_layers();
    auto& cfgData = msg.field_cfgdata().value();

    layers.setBitValue_ram(true);

    CfgdataElement valsetElement;
    valsetElement.field_key().setValue(valKeyId);
    valsetElement.field_val().initField_l().setValue(valValue);

    cfgData.push_back(valsetElement);

    sendMessage(msg);
};
```

I am very happy with the outcome and am looking forward to start adding more functionality.

**Comment by arobenko** [comment]
Looks good, however it is important to remember that "L" field is only 1 byte long. you should change the type of the "valValue" parameter to be something like `std::uint8_t` or even `bool`. In case you'll need longer values you'll have do overload the function where you'll initialize and use other variant members, like  `....initField_u8()...` for example.
