### ISSUE TITLE
g++ terminal build

### ISSUE THREAD

**Issue by abood91** [arobenko/cc.ublox.commsdsl#2]
HI @arobenko and thanks very much for the library. 

I was wondering if its possible to build the example from different directory with terminal and g++.
could you please provide example on how to do that. (my build always complains about missing ublox/message.h file)

**Comment by arobenko** [comment]
Hi @abood91,
I'm not sure I understand your question. I'll try to clarify some things, maybe it will help you understand better.

This project defines UBLOX protocol using [CommsDSL](https://github.com/arobenko/CommsDSL-Specification) schema files. In order to generate C++ code of UBX protocol definition it requires (checks out and builds internally) code generator from [commsdsl](https://github.com/arobenko/commsdsl) project. The outcome of the code generation is different CMake project (also hosted on github as [cc.ublox.generated](https://github.com/arobenko/cc.ublox.generated)). This project also has an [example](https://github.com/arobenko/cc.ublox.commsdsl/tree/master/examples/simple_pos) application, which uses the generated code (which in turn uses [COMMS library](https://github.com/arobenko/comms_champion#comms-library) to define required message classes) to poll and print current position retrieved from connected u-blox receiver.

If you do not want to compile the example application mentioned above, maybe you can use the 
[cc.ublox.generated](https://github.com/arobenko/cc.ublox.generated) generated code directly.

There is [How to Build](https://github.com/arobenko/cc.ublox.commsdsl#how-to-build) instructions for **this** project.
There is a [Generated CMake Project Walkthrough](https://github.com/arobenko/commsdsl/wiki/Generated-CMake-Project-Walkthrough) wiki page with instructions on how to build the **generated** CMake project. You can also take a look at [.travis.yml](https://github.com/arobenko/cc.ublox.commsdsl/blob/master/.travis.yml) and [.appveyor.yml](https://github.com/arobenko/cc.ublox.commsdsl/blob/master/.appveyor.yml) configuration files for external [Travis-CI](https://travis-ci.org/) and [Appveyor](https://www.appveyor.com/) continuous integration build services I'm using. Scroll down to the bottom of the files and see how the builds are invoked.

If it is still unclear to you and/or your build fails, please list the commands (cmake + make) you are using as well as verbose output of your make command. Use `VERBOSE=1` environment variable:
```
$> VERBOSE=1 make
```
Then maybe I'll be able to help you.

**Comment by abood91** [comment]
Hi @arobenko, thanks for the response
I would like to use  CommsDSL and your project and its libraries in other projects, your example code uses cmake and make to build a project, could you give a tutorial or example of how to use this in another projects and to build it with for example g++ on linux 'pkg_cnfig' could be used ? 

also another question is, how to increase the accuracy of the latitude and longitude, right now the example gives only to 5 digits accuracy

**Comment by arobenko** [comment]
About the precision: The lat/lon fields are defined like this:
```
<int name="lon" type="int32" units="deg" scaling="1/10000000" displayDecimals="7" />
```
It means they are serialized by the u-blox receiver as 32bit signed integers. The original floating point value is multiplied by 10000000 and remaining fraction part is dropped. It means by definition you won't get a precision of more than 7 digits after the decimal point. If you want to print floating point value with more than default precision, just use the [setprecision](https://en.cppreference.com/w/cpp/io/manip/setprecision) I/O stream manipulator:
```
std::cout << "POS: lat=" << 
    std::setprecision(8) << comms::units::getDegrees<double>(msg.field_lat()) <<
    "; lon=" << std::setprecision(8) << comms::units::getDegrees<double>(msg.field_lon()) <<
    "; alt=" << comms::units::getMeters<double>(msg.field_height()) << std::endl;
```

As for your other question it still confuses me. I do use g++ to compile my projects on Linux system without any problems. I'm not sure I understand what you mean and I don't think this should be held as public discussion in this ticket. Could you please send me a personal e-mail to arobenko@gmail.com with more details on what exactly you need?

If you are using CMake to drive your main C++ project, then there are ways to integrate the build of externals (such as code generator) using [ExternalProject](https://cmake.org/cmake/help/v3.0/module/ExternalProject.html) and/or [add_custom_target](https://cmake.org/cmake/help/v3.0/command/add_custom_target.html) command. The [CMakeLists.txt](https://github.com/arobenko/cc.ublox.commsdsl/blob/master/CMakeLists.txt) file of this project does exactly that.

If you are using your own build system for your project, then you need to find a way to introduce build of my projects as pre-build stage using some scripting.

At first prepare the headers of the [COMMS library](https://github.com/arobenko/comms_champion#comms-library) for all the communication protocol libraries:
```
$> cmake -DCMAKE_INSTALL_PREFIX=/comms/install/dir -DCC_COMMS_LIB_ONLY=ON /path/to/comms_champion/sources
$> make install
```

Then build the code generator for DSL files:
```
$> cmake -DCMAKE_INSTALL_PREFIX=/commsdsl/install/dir -DCMAKE_BUILD_TYPE=Release -DCOMMSDSL_NO_TESTS=ON /path/to/commsdsl/sources
$> make install
```

The nest stage is generate C++ protocol definition project by invoking `commsdsl2comms` code generator on the DSL schema file(s), like [this line](https://github.com/arobenko/cc.ublox.commsdsl/blob/master/CMakeLists.txt#L231) does for this project.

As the result of the last stage you have protocol definition CMake project generated like [cc.ublox.generated](https://github.com/arobenko/cc.ublox.generated) somewhere.

You can install the protocol definition headers somewhere and add installed "include" subdirectory into official include paths.
```
$> cmake -DOPT_CC_MAIN_INSTALL_DIR=/comms/install/dir -DCMAKE_INSTALL_PREFIX=/path/where/to/install/ublox/protocol/headers    /path/to/generated/ublox/protocol/sources 
$> make install
```
The last installation stage may be unnecessary in case you add generated [include](https://github.com/arobenko/cc.ublox.generated/tree/master/include) directory into official include paths of your project.
Also don't forget to add "include" subdirectory of the COMMS library installation to the include paths of your project.

Hope it helps.
